export const constants = {
    HOME: '/',
    LOGIN: '/login',
    SIGNUP: '/signup',
    PROFILE: '/profile',
    USER_LOGIN: '/user/login',
    USER_SIGNUP: '/user/register',
    SEND_EMAIL: '/mail/send',
    PASSWORD_RESET: '/password/reset',
    PASSWORD_NOTOFICATION: '/password/notification',
    PASSWORD_MAKE_NEW: '/password/make_new',
    PASSWORD_RECOVERY: '/password/recovery',
    VACANCIES: '/vacancies',
    GET_PROFILE: '/profile',
    USER_CONTACTS: '/user/contacts',
    CREATE_JOB: "/createjob",
    PHOTO_UPLOAD: 'https://futurama.cf/upload/',
    PHOTO_PLACEHOLDER: 'https://futurama.cf/upload/avatarPlaceholder7652.png',
};
