export const constants = {
    HOME: '/',
    LOGIN: '/login',
    SIGNUP: '/signup',
    PROFILE: '/profile',
    USER_LOGIN: '/user/login',
    USER_SIGNUP: '/user/register',
    SEND_EMAIL: '/mail/send',
    PASSWORD_RESET: '/password/reset',
    PASSWORD_MAKE_NEW: '/password/make_new',
    PASSWORD_RECOVERY: '/password/recovery',
    VACANCIES: '/vacancies',
    GET_VACANCIES: 'search_work/vacancies/',
    GET_PROFILE: '/profile',
    USER_CONTACTS: '/user/contacts',
    PHOTO_UPLOAD: 'https://futurama.cf:3011/upload/',
    PHOTO_PLACEHOLDER: 'https://futurama.cf:3011/upload/avatarPlaceholder7652.png',
    COMPANY_PLACEHOLDER: "https://placehold.jp/120x120.png",
    VACANCY_DETAILS: '/vacancy/:id'
};
